//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.269.
// 
#pragma warning disable 1591

namespace ItineraryBuilder.SchedulesConnectionsService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SchedulesConnectionsSOAPBinding", Namespace="http://www.pathfinder-xml.com/SchedulesConnectionsService.wsdl")]
    public partial class SchedulesConnectionsService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SchedulesConnectionsOperationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SchedulesConnectionsService() {
            this.Url = global::ItineraryBuilder.Properties.Settings.Default.ItineraryBuilder_SchedulesConnectionsService_SchedulesConnectionsService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SchedulesConnectionsOperationCompletedEventHandler SchedulesConnectionsOperationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("SchedulesConnectionsResponse", Namespace="http://pathfinder-xml/SchedulesConnectionsService.xsd")]
        public SchedulesConnectionsResponse SchedulesConnectionsOperation([System.Xml.Serialization.XmlElementAttribute(Namespace="http://pathfinder-xml/SchedulesConnectionsService.xsd")] SchedulesConnectionsRequest SchedulesConnectionsRequest) {
            object[] results = this.Invoke("SchedulesConnectionsOperation", new object[] {
                        SchedulesConnectionsRequest});
            return ((SchedulesConnectionsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SchedulesConnectionsOperationAsync(SchedulesConnectionsRequest SchedulesConnectionsRequest) {
            this.SchedulesConnectionsOperationAsync(SchedulesConnectionsRequest, null);
        }
        
        /// <remarks/>
        public void SchedulesConnectionsOperationAsync(SchedulesConnectionsRequest SchedulesConnectionsRequest, object userState) {
            if ((this.SchedulesConnectionsOperationOperationCompleted == null)) {
                this.SchedulesConnectionsOperationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSchedulesConnectionsOperationOperationCompleted);
            }
            this.InvokeAsync("SchedulesConnectionsOperation", new object[] {
                        SchedulesConnectionsRequest}, this.SchedulesConnectionsOperationOperationCompleted, userState);
        }
        
        private void OnSchedulesConnectionsOperationOperationCompleted(object arg) {
            if ((this.SchedulesConnectionsOperationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SchedulesConnectionsOperationCompleted(this, new SchedulesConnectionsOperationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pathfinder-xml/SchedulesConnectionsService.xsd")]
    public partial class SchedulesConnectionsRequest {
        
        private Login loginField;
        
        private Airline[] carrierField;
        
        private Airport originField;
        
        private Airport destinationField;
        
        private Airport[] allowedConnectionField;
        
        private Airport[] excludedConnectionField;
        
        private string codeshareTypeField;
        
        private string connectionTypeField;
        
        private string flightNumberField;
        
        private string flightTypeField;
        
        private System.DateTime fromField;
        
        private bool includeRatingsField;
        
        private bool includeRatingsFieldSpecified;
        
        private string serviceTypeField;
        
        private System.DateTime toField;
        
        private bool toFieldSpecified;
        
        private bool useArrivalDatesField;
        
        private bool useArrivalDatesFieldSpecified;
        
        /// <remarks/>
        public Login Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Carrier")]
        public Airline[] Carrier {
            get {
                return this.carrierField;
            }
            set {
                this.carrierField = value;
            }
        }
        
        /// <remarks/>
        public Airport Origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        public Airport Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AllowedConnection")]
        public Airport[] AllowedConnection {
            get {
                return this.allowedConnectionField;
            }
            set {
                this.allowedConnectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExcludedConnection")]
        public Airport[] ExcludedConnection {
            get {
                return this.excludedConnectionField;
            }
            set {
                this.excludedConnectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodeshareType {
            get {
                return this.codeshareTypeField;
            }
            set {
                this.codeshareTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ConnectionType {
            get {
                return this.connectionTypeField;
            }
            set {
                this.connectionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FlightNumber {
            get {
                return this.flightNumberField;
            }
            set {
                this.flightNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FlightType {
            get {
                return this.flightTypeField;
            }
            set {
                this.flightTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IncludeRatings {
            get {
                return this.includeRatingsField;
            }
            set {
                this.includeRatingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IncludeRatingsSpecified {
            get {
                return this.includeRatingsFieldSpecified;
            }
            set {
                this.includeRatingsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ServiceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ToSpecified {
            get {
                return this.toFieldSpecified;
            }
            set {
                this.toFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool UseArrivalDates {
            get {
                return this.useArrivalDatesField;
            }
            set {
                this.useArrivalDatesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UseArrivalDatesSpecified {
            get {
                return this.useArrivalDatesFieldSpecified;
            }
            set {
                this.useArrivalDatesFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pathfinder-xml/SchedulesConnectionsService.xsd")]
    public partial class Login {
        
        private string accountIdField;
        
        private string guidField;
        
        private string passwordField;
        
        private string userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AccountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pathfinder-xml/SchedulesConnectionsService.xsd")]
    public partial class Rating {
        
        private float delayCumulativePercentField;
        
        private bool delayCumulativePercentFieldSpecified;
        
        private float delayStarsField;
        
        private bool delayStarsFieldSpecified;
        
        private float ontimeCumulativePercentField;
        
        private bool ontimeCumulativePercentFieldSpecified;
        
        private float ontimeStarsField;
        
        private bool ontimeStarsFieldSpecified;
        
        private float overallStarsField;
        
        private bool overallStarsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float DelayCumulativePercent {
            get {
                return this.delayCumulativePercentField;
            }
            set {
                this.delayCumulativePercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DelayCumulativePercentSpecified {
            get {
                return this.delayCumulativePercentFieldSpecified;
            }
            set {
                this.delayCumulativePercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float DelayStars {
            get {
                return this.delayStarsField;
            }
            set {
                this.delayStarsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DelayStarsSpecified {
            get {
                return this.delayStarsFieldSpecified;
            }
            set {
                this.delayStarsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float OntimeCumulativePercent {
            get {
                return this.ontimeCumulativePercentField;
            }
            set {
                this.ontimeCumulativePercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OntimeCumulativePercentSpecified {
            get {
                return this.ontimeCumulativePercentFieldSpecified;
            }
            set {
                this.ontimeCumulativePercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float OntimeStars {
            get {
                return this.ontimeStarsField;
            }
            set {
                this.ontimeStarsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OntimeStarsSpecified {
            get {
                return this.ontimeStarsFieldSpecified;
            }
            set {
                this.ontimeStarsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float OverallStars {
            get {
                return this.overallStarsField;
            }
            set {
                this.overallStarsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OverallStarsSpecified {
            get {
                return this.overallStarsFieldSpecified;
            }
            set {
                this.overallStarsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pathfinder-xml/SchedulesConnectionsService.xsd")]
    public partial class Statistics {
        
        private int cancelledField;
        
        private bool cancelledFieldSpecified;
        
        private int delayMaxField;
        
        private bool delayMaxFieldSpecified;
        
        private float delayMeanField;
        
        private bool delayMeanFieldSpecified;
        
        private int delayMinField;
        
        private bool delayMinFieldSpecified;
        
        private int delayObservationsField;
        
        private bool delayObservationsFieldSpecified;
        
        private float delayStandardDeviationField;
        
        private bool delayStandardDeviationFieldSpecified;
        
        private int divertedField;
        
        private bool divertedFieldSpecified;
        
        private int late15Field;
        
        private bool late15FieldSpecified;
        
        private int late30Field;
        
        private bool late30FieldSpecified;
        
        private int late45Field;
        
        private bool late45FieldSpecified;
        
        private int observationsField;
        
        private bool observationsFieldSpecified;
        
        private float ontimePercentField;
        
        private bool ontimePercentFieldSpecified;
        
        private int ontimeField;
        
        private bool ontimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Cancelled {
            get {
                return this.cancelledField;
            }
            set {
                this.cancelledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CancelledSpecified {
            get {
                return this.cancelledFieldSpecified;
            }
            set {
                this.cancelledFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int DelayMax {
            get {
                return this.delayMaxField;
            }
            set {
                this.delayMaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DelayMaxSpecified {
            get {
                return this.delayMaxFieldSpecified;
            }
            set {
                this.delayMaxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float DelayMean {
            get {
                return this.delayMeanField;
            }
            set {
                this.delayMeanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DelayMeanSpecified {
            get {
                return this.delayMeanFieldSpecified;
            }
            set {
                this.delayMeanFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int DelayMin {
            get {
                return this.delayMinField;
            }
            set {
                this.delayMinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DelayMinSpecified {
            get {
                return this.delayMinFieldSpecified;
            }
            set {
                this.delayMinFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int DelayObservations {
            get {
                return this.delayObservationsField;
            }
            set {
                this.delayObservationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DelayObservationsSpecified {
            get {
                return this.delayObservationsFieldSpecified;
            }
            set {
                this.delayObservationsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float DelayStandardDeviation {
            get {
                return this.delayStandardDeviationField;
            }
            set {
                this.delayStandardDeviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DelayStandardDeviationSpecified {
            get {
                return this.delayStandardDeviationFieldSpecified;
            }
            set {
                this.delayStandardDeviationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Diverted {
            get {
                return this.divertedField;
            }
            set {
                this.divertedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DivertedSpecified {
            get {
                return this.divertedFieldSpecified;
            }
            set {
                this.divertedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Late15 {
            get {
                return this.late15Field;
            }
            set {
                this.late15Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Late15Specified {
            get {
                return this.late15FieldSpecified;
            }
            set {
                this.late15FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Late30 {
            get {
                return this.late30Field;
            }
            set {
                this.late30Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Late30Specified {
            get {
                return this.late30FieldSpecified;
            }
            set {
                this.late30FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Late45 {
            get {
                return this.late45Field;
            }
            set {
                this.late45Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Late45Specified {
            get {
                return this.late45FieldSpecified;
            }
            set {
                this.late45FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Observations {
            get {
                return this.observationsField;
            }
            set {
                this.observationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ObservationsSpecified {
            get {
                return this.observationsFieldSpecified;
            }
            set {
                this.observationsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float OntimePercent {
            get {
                return this.ontimePercentField;
            }
            set {
                this.ontimePercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OntimePercentSpecified {
            get {
                return this.ontimePercentFieldSpecified;
            }
            set {
                this.ontimePercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Ontime {
            get {
                return this.ontimeField;
            }
            set {
                this.ontimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OntimeSpecified {
            get {
                return this.ontimeFieldSpecified;
            }
            set {
                this.ontimeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pathfinder-xml/SchedulesConnectionsService.xsd")]
    public partial class FlightRating {
        
        private Airline airlineField;
        
        private Airport departureAirportField;
        
        private Airport arrivalAirportField;
        
        private Statistics statisticsField;
        
        private Rating ratingField;
        
        private int codesharesField;
        
        private bool codesharesFieldSpecified;
        
        private int directsField;
        
        private bool directsFieldSpecified;
        
        private string flightNumberField;
        
        private int operatedFlightsField;
        
        private bool operatedFlightsFieldSpecified;
        
        /// <remarks/>
        public Airline Airline {
            get {
                return this.airlineField;
            }
            set {
                this.airlineField = value;
            }
        }
        
        /// <remarks/>
        public Airport DepartureAirport {
            get {
                return this.departureAirportField;
            }
            set {
                this.departureAirportField = value;
            }
        }
        
        /// <remarks/>
        public Airport ArrivalAirport {
            get {
                return this.arrivalAirportField;
            }
            set {
                this.arrivalAirportField = value;
            }
        }
        
        /// <remarks/>
        public Statistics Statistics {
            get {
                return this.statisticsField;
            }
            set {
                this.statisticsField = value;
            }
        }
        
        /// <remarks/>
        public Rating Rating {
            get {
                return this.ratingField;
            }
            set {
                this.ratingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Codeshares {
            get {
                return this.codesharesField;
            }
            set {
                this.codesharesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodesharesSpecified {
            get {
                return this.codesharesFieldSpecified;
            }
            set {
                this.codesharesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Directs {
            get {
                return this.directsField;
            }
            set {
                this.directsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DirectsSpecified {
            get {
                return this.directsFieldSpecified;
            }
            set {
                this.directsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FlightNumber {
            get {
                return this.flightNumberField;
            }
            set {
                this.flightNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int OperatedFlights {
            get {
                return this.operatedFlightsField;
            }
            set {
                this.operatedFlightsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OperatedFlightsSpecified {
            get {
                return this.operatedFlightsFieldSpecified;
            }
            set {
                this.operatedFlightsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pathfinder-xml/SchedulesConnectionsService.xsd")]
    public partial class Airline {
        
        private string airlineCodeField;
        
        private string iATACodeField;
        
        private string iCAOCodeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AirlineCode {
            get {
                return this.airlineCodeField;
            }
            set {
                this.airlineCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IATACode {
            get {
                return this.iATACodeField;
            }
            set {
                this.iATACodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ICAOCode {
            get {
                return this.iCAOCodeField;
            }
            set {
                this.iCAOCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pathfinder-xml/SchedulesConnectionsService.xsd")]
    public partial class Airport {
        
        private string airportCodeField;
        
        private string fAACodeField;
        
        private string iATACodeField;
        
        private string iCAOCodeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AirportCode {
            get {
                return this.airportCodeField;
            }
            set {
                this.airportCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FAACode {
            get {
                return this.fAACodeField;
            }
            set {
                this.fAACodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IATACode {
            get {
                return this.iATACodeField;
            }
            set {
                this.iATACodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ICAOCode {
            get {
                return this.iCAOCodeField;
            }
            set {
                this.iCAOCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pathfinder-xml/SchedulesConnectionsService.xsd")]
    public partial class ConnectionsAircraftType {
        
        private string aircraftTypeCodeField;
        
        private string aircraftTypeNameField;
        
        private bool jetField;
        
        private bool jetFieldSpecified;
        
        private bool regionalField;
        
        private bool regionalFieldSpecified;
        
        private bool turbopropField;
        
        private bool turbopropFieldSpecified;
        
        private bool wideBodyField;
        
        private bool wideBodyFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AircraftTypeCode {
            get {
                return this.aircraftTypeCodeField;
            }
            set {
                this.aircraftTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AircraftTypeName {
            get {
                return this.aircraftTypeNameField;
            }
            set {
                this.aircraftTypeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Jet {
            get {
                return this.jetField;
            }
            set {
                this.jetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JetSpecified {
            get {
                return this.jetFieldSpecified;
            }
            set {
                this.jetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Regional {
            get {
                return this.regionalField;
            }
            set {
                this.regionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegionalSpecified {
            get {
                return this.regionalFieldSpecified;
            }
            set {
                this.regionalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Turboprop {
            get {
                return this.turbopropField;
            }
            set {
                this.turbopropField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TurbopropSpecified {
            get {
                return this.turbopropFieldSpecified;
            }
            set {
                this.turbopropFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool WideBody {
            get {
                return this.wideBodyField;
            }
            set {
                this.wideBodyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WideBodySpecified {
            get {
                return this.wideBodyFieldSpecified;
            }
            set {
                this.wideBodyFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pathfinder-xml/SchedulesConnectionsService.xsd")]
    public partial class ConnectionsFlightId {
        
        private Airline carrierField;
        
        private string flightNumberField;
        
        /// <remarks/>
        public Airline Carrier {
            get {
                return this.carrierField;
            }
            set {
                this.carrierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FlightNumber {
            get {
                return this.flightNumberField;
            }
            set {
                this.flightNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pathfinder-xml/SchedulesConnectionsService.xsd")]
    public partial class ConnectionsFlightLeg {
        
        private ConnectionsFlightId flightIdField;
        
        private ConnectionsFlightId operatorField;
        
        private ConnectionsFlightId[] codeshareField;
        
        private AirportDetail departureAirportField;
        
        private AirportDetail arrivalAirportField;
        
        private AirportDetail[] stopField;
        
        private ConnectionsAircraftType[] equipmentField;
        
        private FlightRating[] ratingFlightField;
        
        private int arrivalDateAdjustmentField;
        
        private bool arrivalDateAdjustmentFieldSpecified;
        
        private string arrivalTerminalField;
        
        private string arrivalTimeField;
        
        private bool codeshare1Field;
        
        private bool codeshare1FieldSpecified;
        
        private int departureDateAdjustmentField;
        
        private bool departureDateAdjustmentFieldSpecified;
        
        private string departureTerminalField;
        
        private string departureTimeField;
        
        private int distanceMilesField;
        
        private bool distanceMilesFieldSpecified;
        
        private int flightDurationMinutesField;
        
        private bool flightDurationMinutesFieldSpecified;
        
        private int layoverDurationMinutesField;
        
        private bool layoverDurationMinutesFieldSpecified;
        
        private string wetleaseInfoField;
        
        /// <remarks/>
        public ConnectionsFlightId FlightId {
            get {
                return this.flightIdField;
            }
            set {
                this.flightIdField = value;
            }
        }
        
        /// <remarks/>
        public ConnectionsFlightId Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Codeshare")]
        public ConnectionsFlightId[] Codeshare {
            get {
                return this.codeshareField;
            }
            set {
                this.codeshareField = value;
            }
        }
        
        /// <remarks/>
        public AirportDetail DepartureAirport {
            get {
                return this.departureAirportField;
            }
            set {
                this.departureAirportField = value;
            }
        }
        
        /// <remarks/>
        public AirportDetail ArrivalAirport {
            get {
                return this.arrivalAirportField;
            }
            set {
                this.arrivalAirportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Stop")]
        public AirportDetail[] Stop {
            get {
                return this.stopField;
            }
            set {
                this.stopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Equipment")]
        public ConnectionsAircraftType[] Equipment {
            get {
                return this.equipmentField;
            }
            set {
                this.equipmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RatingFlight")]
        public FlightRating[] RatingFlight {
            get {
                return this.ratingFlightField;
            }
            set {
                this.ratingFlightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ArrivalDateAdjustment {
            get {
                return this.arrivalDateAdjustmentField;
            }
            set {
                this.arrivalDateAdjustmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ArrivalDateAdjustmentSpecified {
            get {
                return this.arrivalDateAdjustmentFieldSpecified;
            }
            set {
                this.arrivalDateAdjustmentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ArrivalTerminal {
            get {
                return this.arrivalTerminalField;
            }
            set {
                this.arrivalTerminalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ArrivalTime {
            get {
                return this.arrivalTimeField;
            }
            set {
                this.arrivalTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Codeshare")]
        public bool Codeshare1 {
            get {
                return this.codeshare1Field;
            }
            set {
                this.codeshare1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Codeshare1Specified {
            get {
                return this.codeshare1FieldSpecified;
            }
            set {
                this.codeshare1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int DepartureDateAdjustment {
            get {
                return this.departureDateAdjustmentField;
            }
            set {
                this.departureDateAdjustmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DepartureDateAdjustmentSpecified {
            get {
                return this.departureDateAdjustmentFieldSpecified;
            }
            set {
                this.departureDateAdjustmentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DepartureTerminal {
            get {
                return this.departureTerminalField;
            }
            set {
                this.departureTerminalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DepartureTime {
            get {
                return this.departureTimeField;
            }
            set {
                this.departureTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int DistanceMiles {
            get {
                return this.distanceMilesField;
            }
            set {
                this.distanceMilesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DistanceMilesSpecified {
            get {
                return this.distanceMilesFieldSpecified;
            }
            set {
                this.distanceMilesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int FlightDurationMinutes {
            get {
                return this.flightDurationMinutesField;
            }
            set {
                this.flightDurationMinutesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlightDurationMinutesSpecified {
            get {
                return this.flightDurationMinutesFieldSpecified;
            }
            set {
                this.flightDurationMinutesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int LayoverDurationMinutes {
            get {
                return this.layoverDurationMinutesField;
            }
            set {
                this.layoverDurationMinutesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LayoverDurationMinutesSpecified {
            get {
                return this.layoverDurationMinutesFieldSpecified;
            }
            set {
                this.layoverDurationMinutesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string WetleaseInfo {
            get {
                return this.wetleaseInfoField;
            }
            set {
                this.wetleaseInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pathfinder-xml/SchedulesConnectionsService.xsd")]
    public partial class AirportDetail {
        
        private string airportCodeField;
        
        private string cityField;
        
        private string countryCodeField;
        
        private string fAACodeField;
        
        private string iATACodeField;
        
        private string iCAOCodeField;
        
        private string nameField;
        
        private string stateCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AirportCode {
            get {
                return this.airportCodeField;
            }
            set {
                this.airportCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FAACode {
            get {
                return this.fAACodeField;
            }
            set {
                this.fAACodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IATACode {
            get {
                return this.iATACodeField;
            }
            set {
                this.iATACodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ICAOCode {
            get {
                return this.iCAOCodeField;
            }
            set {
                this.iCAOCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StateCode {
            get {
                return this.stateCodeField;
            }
            set {
                this.stateCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pathfinder-xml/SchedulesConnectionsService.xsd")]
    public partial class ConnectionsFlight {
        
        private AirportDetail departureAirportField;
        
        private AirportDetail arrivalAirportField;
        
        private ConnectionsFlightLeg[] flightLegField;
        
        private int arrivalDateAdjustmentField;
        
        private bool arrivalDateAdjustmentFieldSpecified;
        
        private string arrivalTimeField;
        
        private string departureDateFromField;
        
        private string departureDateToField;
        
        private string departureDaysOfWeekField;
        
        private string departureTimeField;
        
        private int distanceMilesField;
        
        private bool distanceMilesFieldSpecified;
        
        private int flightDurationMinutesField;
        
        private bool flightDurationMinutesFieldSpecified;
        
        private string flightTypeField;
        
        private int layoverDurationMinutesField;
        
        private bool layoverDurationMinutesFieldSpecified;
        
        private string serviceTypeField;
        
        /// <remarks/>
        public AirportDetail DepartureAirport {
            get {
                return this.departureAirportField;
            }
            set {
                this.departureAirportField = value;
            }
        }
        
        /// <remarks/>
        public AirportDetail ArrivalAirport {
            get {
                return this.arrivalAirportField;
            }
            set {
                this.arrivalAirportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FlightLeg")]
        public ConnectionsFlightLeg[] FlightLeg {
            get {
                return this.flightLegField;
            }
            set {
                this.flightLegField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ArrivalDateAdjustment {
            get {
                return this.arrivalDateAdjustmentField;
            }
            set {
                this.arrivalDateAdjustmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ArrivalDateAdjustmentSpecified {
            get {
                return this.arrivalDateAdjustmentFieldSpecified;
            }
            set {
                this.arrivalDateAdjustmentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ArrivalTime {
            get {
                return this.arrivalTimeField;
            }
            set {
                this.arrivalTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DepartureDateFrom {
            get {
                return this.departureDateFromField;
            }
            set {
                this.departureDateFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DepartureDateTo {
            get {
                return this.departureDateToField;
            }
            set {
                this.departureDateToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DepartureDaysOfWeek {
            get {
                return this.departureDaysOfWeekField;
            }
            set {
                this.departureDaysOfWeekField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DepartureTime {
            get {
                return this.departureTimeField;
            }
            set {
                this.departureTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int DistanceMiles {
            get {
                return this.distanceMilesField;
            }
            set {
                this.distanceMilesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DistanceMilesSpecified {
            get {
                return this.distanceMilesFieldSpecified;
            }
            set {
                this.distanceMilesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int FlightDurationMinutes {
            get {
                return this.flightDurationMinutesField;
            }
            set {
                this.flightDurationMinutesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlightDurationMinutesSpecified {
            get {
                return this.flightDurationMinutesFieldSpecified;
            }
            set {
                this.flightDurationMinutesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FlightType {
            get {
                return this.flightTypeField;
            }
            set {
                this.flightTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int LayoverDurationMinutes {
            get {
                return this.layoverDurationMinutesField;
            }
            set {
                this.layoverDurationMinutesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LayoverDurationMinutesSpecified {
            get {
                return this.layoverDurationMinutesFieldSpecified;
            }
            set {
                this.layoverDurationMinutesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ServiceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pathfinder-xml/SchedulesConnectionsService.xsd")]
    public partial class Error {
        
        private string messageField;
        
        private string stackTraceField;
        
        private string majorCodeField;
        
        private string minorCodeField;
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string StackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MajorCode {
            get {
                return this.majorCodeField;
            }
            set {
                this.majorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MinorCode {
            get {
                return this.minorCodeField;
            }
            set {
                this.minorCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pathfinder-xml/SchedulesConnectionsService.xsd")]
    public partial class SchedulesConnectionsResponse {
        
        private Error errorField;
        
        private ConnectionsFlight[] flightField;
        
        /// <remarks/>
        public Error Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Flight")]
        public ConnectionsFlight[] Flight {
            get {
                return this.flightField;
            }
            set {
                this.flightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SchedulesConnectionsOperationCompletedEventHandler(object sender, SchedulesConnectionsOperationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SchedulesConnectionsOperationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SchedulesConnectionsOperationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SchedulesConnectionsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SchedulesConnectionsResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591