//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4971
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pathfinder-xml/SchedulesConnectionsService.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pathfinder-xml/SchedulesConnectionsService.xsd", IsNullable=false)]
public partial class DepartureAirport {
    
    private string airportCodeField;
    
    private string cityField;
    
    private string countryCodeField;
    
    private string fAACodeField;
    
    private string iATACodeField;
    
    private string iCAOCodeField;
    
    private string nameField;
    
    private string stateCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AirportCode {
        get {
            return this.airportCodeField;
        }
        set {
            this.airportCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CountryCode {
        get {
            return this.countryCodeField;
        }
        set {
            this.countryCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FAACode {
        get {
            return this.fAACodeField;
        }
        set {
            this.fAACodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string IATACode {
        get {
            return this.iATACodeField;
        }
        set {
            this.iATACodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ICAOCode {
        get {
            return this.iCAOCodeField;
        }
        set {
            this.iCAOCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StateCode {
        get {
            return this.stateCodeField;
        }
        set {
            this.stateCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pathfinder-xml/SchedulesConnectionsService.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pathfinder-xml/SchedulesConnectionsService.xsd", IsNullable=false)]
public partial class ArrivalAirport {
    
    private string airportCodeField;
    
    private string cityField;
    
    private string countryCodeField;
    
    private string iATACodeField;
    
    private string iCAOCodeField;
    
    private string nameField;
    
    private string stateCodeField;
    
    private string fAACodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AirportCode {
        get {
            return this.airportCodeField;
        }
        set {
            this.airportCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CountryCode {
        get {
            return this.countryCodeField;
        }
        set {
            this.countryCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string IATACode {
        get {
            return this.iATACodeField;
        }
        set {
            this.iATACodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ICAOCode {
        get {
            return this.iCAOCodeField;
        }
        set {
            this.iCAOCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StateCode {
        get {
            return this.stateCodeField;
        }
        set {
            this.stateCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FAACode {
        get {
            return this.fAACodeField;
        }
        set {
            this.fAACodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pathfinder-xml/SchedulesConnectionsService.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pathfinder-xml/SchedulesConnectionsService.xsd", IsNullable=false)]
public partial class SchedulesConnectionsResponse {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ArrivalAirport", typeof(ArrivalAirport))]
    [System.Xml.Serialization.XmlElementAttribute("DepartureAirport", typeof(DepartureAirport))]
    [System.Xml.Serialization.XmlElementAttribute("Flight", typeof(SchedulesConnectionsResponseFlight))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pathfinder-xml/SchedulesConnectionsService.xsd")]
public partial class SchedulesConnectionsResponseFlight {
    
    private DepartureAirport[] departureAirportField;
    
    private ArrivalAirport[] arrivalAirportField;
    
    private SchedulesConnectionsResponseFlightFlightLeg[] flightLegField;
    
    private string arrivalDateAdjustmentField;
    
    private string arrivalTimeField;
    
    private string departureDateFromField;
    
    private string departureDateToField;
    
    private string departureDaysOfWeekField;
    
    private string departureTimeField;
    
    private int distanceMilesField;
    
    private int flightDurationMinutesField;
    
    private string flightTypeField;
    
    private string layoverDurationMinutesField;
    
    private string serviceTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DepartureAirport")]
    public DepartureAirport[] DepartureAirport {
        get {
            return this.departureAirportField;
        }
        set {
            this.departureAirportField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ArrivalAirport")]
    public ArrivalAirport[] ArrivalAirport {
        get {
            return this.arrivalAirportField;
        }
        set {
            this.arrivalAirportField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FlightLeg")]
    public SchedulesConnectionsResponseFlightFlightLeg[] FlightLeg {
        get {
            return this.flightLegField;
        }
        set {
            this.flightLegField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ArrivalDateAdjustment {
        get {
            return this.arrivalDateAdjustmentField;
        }
        set {
            this.arrivalDateAdjustmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ArrivalTime {
        get {
            return this.arrivalTimeField;
        }
        set {
            this.arrivalTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DepartureDateFrom {
        get {
            return this.departureDateFromField;
        }
        set {
            this.departureDateFromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DepartureDateTo {
        get {
            return this.departureDateToField;
        }
        set {
            this.departureDateToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DepartureDaysOfWeek {
        get {
            return this.departureDaysOfWeekField;
        }
        set {
            this.departureDaysOfWeekField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DepartureTime {
        get {
            return this.departureTimeField;
        }
        set {
            this.departureTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int DistanceMiles {
        get {
            return this.distanceMilesField;
        }
        set {
            this.distanceMilesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int FlightDurationMinutes {
        get {
            return this.flightDurationMinutesField;
        }
        set {
            this.flightDurationMinutesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FlightType {
        get {
            return this.flightTypeField;
        }
        set {
            this.flightTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LayoverDurationMinutes {
        get {
            return this.layoverDurationMinutesField;
        }
        set {
            this.layoverDurationMinutesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ServiceType {
        get {
            return this.serviceTypeField;
        }
        set {
            this.serviceTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pathfinder-xml/SchedulesConnectionsService.xsd")]
public partial class SchedulesConnectionsResponseFlightFlightLeg {
    
    private SchedulesConnectionsResponseFlightFlightLegFlightId[] flightIdField;
    
    private DepartureAirport[] departureAirportField;
    
    private ArrivalAirport[] arrivalAirportField;
    
    private SchedulesConnectionsResponseFlightFlightLegStop[] stopField;
    
    private SchedulesConnectionsResponseFlightFlightLegEquipment[] equipmentField;
    
    private string codeshareField;
    
    private string arrivalDateAdjustmentField;
    
    private string arrivalTimeField;
    
    private string departureDateAdjustmentField;
    
    private string departureTerminalField;
    
    private string departureTimeField;
    
    private string distanceMilesField;
    
    private string flightDurationMinutesField;
    
    private string layoverDurationMinutesField;
    
    private string wetleaseInfoField;
    
    private string arrivalTerminalField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FlightId")]
    public SchedulesConnectionsResponseFlightFlightLegFlightId[] FlightId {
        get {
            return this.flightIdField;
        }
        set {
            this.flightIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DepartureAirport")]
    public DepartureAirport[] DepartureAirport {
        get {
            return this.departureAirportField;
        }
        set {
            this.departureAirportField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ArrivalAirport")]
    public ArrivalAirport[] ArrivalAirport {
        get {
            return this.arrivalAirportField;
        }
        set {
            this.arrivalAirportField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Stop")]
    public SchedulesConnectionsResponseFlightFlightLegStop[] Stop {
        get {
            return this.stopField;
        }
        set {
            this.stopField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Equipment")]
    public SchedulesConnectionsResponseFlightFlightLegEquipment[] Equipment {
        get {
            return this.equipmentField;
        }
        set {
            this.equipmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Codeshare {
        get {
            return this.codeshareField;
        }
        set {
            this.codeshareField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ArrivalDateAdjustment {
        get {
            return this.arrivalDateAdjustmentField;
        }
        set {
            this.arrivalDateAdjustmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ArrivalTime {
        get {
            return this.arrivalTimeField;
        }
        set {
            this.arrivalTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DepartureDateAdjustment {
        get {
            return this.departureDateAdjustmentField;
        }
        set {
            this.departureDateAdjustmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DepartureTerminal {
        get {
            return this.departureTerminalField;
        }
        set {
            this.departureTerminalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DepartureTime {
        get {
            return this.departureTimeField;
        }
        set {
            this.departureTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DistanceMiles {
        get {
            return this.distanceMilesField;
        }
        set {
            this.distanceMilesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FlightDurationMinutes {
        get {
            return this.flightDurationMinutesField;
        }
        set {
            this.flightDurationMinutesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LayoverDurationMinutes {
        get {
            return this.layoverDurationMinutesField;
        }
        set {
            this.layoverDurationMinutesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string WetleaseInfo {
        get {
            return this.wetleaseInfoField;
        }
        set {
            this.wetleaseInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ArrivalTerminal {
        get {
            return this.arrivalTerminalField;
        }
        set {
            this.arrivalTerminalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pathfinder-xml/SchedulesConnectionsService.xsd")]
public partial class SchedulesConnectionsResponseFlightFlightLegFlightId {
    
    private SchedulesConnectionsResponseFlightFlightLegFlightIdCarrier[] carrierField;
    
    private string flightNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Carrier")]
    public SchedulesConnectionsResponseFlightFlightLegFlightIdCarrier[] Carrier {
        get {
            return this.carrierField;
        }
        set {
            this.carrierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FlightNumber {
        get {
            return this.flightNumberField;
        }
        set {
            this.flightNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pathfinder-xml/SchedulesConnectionsService.xsd")]
public partial class SchedulesConnectionsResponseFlightFlightLegFlightIdCarrier {
    
    private string airlineCodeField;
    
    private string iATACodeField;
    
    private string iCAOCodeField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AirlineCode {
        get {
            return this.airlineCodeField;
        }
        set {
            this.airlineCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string IATACode {
        get {
            return this.iATACodeField;
        }
        set {
            this.iATACodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ICAOCode {
        get {
            return this.iCAOCodeField;
        }
        set {
            this.iCAOCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pathfinder-xml/SchedulesConnectionsService.xsd")]
public partial class SchedulesConnectionsResponseFlightFlightLegStop {
    
    private string airportCodeField;
    
    private string cityField;
    
    private string countryCodeField;
    
    private string iATACodeField;
    
    private string iCAOCodeField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AirportCode {
        get {
            return this.airportCodeField;
        }
        set {
            this.airportCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CountryCode {
        get {
            return this.countryCodeField;
        }
        set {
            this.countryCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string IATACode {
        get {
            return this.iATACodeField;
        }
        set {
            this.iATACodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ICAOCode {
        get {
            return this.iCAOCodeField;
        }
        set {
            this.iCAOCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pathfinder-xml/SchedulesConnectionsService.xsd")]
public partial class SchedulesConnectionsResponseFlightFlightLegEquipment {
    
    private string aircraftTypeCodeField;
    
    private string aircraftTypeNameField;
    
    private string jetField;
    
    private string regionalField;
    
    private string turbopropField;
    
    private string wideBodyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AircraftTypeCode {
        get {
            return this.aircraftTypeCodeField;
        }
        set {
            this.aircraftTypeCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AircraftTypeName {
        get {
            return this.aircraftTypeNameField;
        }
        set {
            this.aircraftTypeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Jet {
        get {
            return this.jetField;
        }
        set {
            this.jetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Regional {
        get {
            return this.regionalField;
        }
        set {
            this.regionalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Turboprop {
        get {
            return this.turbopropField;
        }
        set {
            this.turbopropField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string WideBody {
        get {
            return this.wideBodyField;
        }
        set {
            this.wideBodyField = value;
        }
    }
}
